[package]
name = "capture"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.15"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
governor = "0.5.1"
tower_governor = "0.0.4"
time = "0.3.20"
tower-http = {version = "0.4.0", features = ["trace"]}
bytes = "1"
anyhow = "1.0"
flate2 = "1.0"
base64 = "0.21.1"

[dev-dependencies]
mockall = "0.11.2"
